разметка главной страницы
htmlacademy-htmlcss/22988-device-32 pull request #2
Opened 2021-09-24 20:00 UTC by BesedinEgor

2021-09-25 17:21 UTC, BesedinEgor commented on index.html
> +  <!-- <link rel="stylesheet" href="css/style.css"> -->
закомментил css файл, ввиду того, что забегал чуть вперед

2021-09-25 17:21 UTC, BesedinEgor commented on index.html
> +              </div> -->
закомментирован по причине отсутствия в ТЗ верстки выпадающих списков(элементов)

2021-09-26 14:02 UTC, avylando requested changes
Привет!
Могу сказать что мне в целом понравилась твоя работа, очень хорошая разметка, кое-где даже предусмотрел сеточные элементы + решил применить БЭМ - это только в плюс тебе)

По замечаниям поправь пожалуйста, и сделай ПР актуальным заданию, к которому он привязан - то есть к Разметке главной страницы. Все следующие ПР должны быть тоже привязаны только к своему заданию, то есть схема всегда такая - 1задание = 1 ПР

Все что не относится к этому заданию - удали пока что и добавь в следующий ПР. Для каталога я тоже написал замечания, так что можешь их сразу поправить перед отправкой реквеста

Проверять стили будем уже после того как два задания по разметке будут выполнены

2021-09-26 15:48 UTC, BesedinEgor commented on catalog.html
> +                                <span class="control-mark"></span>
ок, я тоже думал делать это через css, но на разборе в лайве это рекомендовали делать именно так)

2021-09-26 16:00 UTC, BesedinEgor commented on index.html
> +        <span class="slider__number"></span>
имеешь ввиду span? я поначалу думал о том, что можно будет это реализовать через псевдоэлемент и счетчик counter-increment

2021-09-26 16:31 UTC, BesedinEgor commented on index.html
> +        <div class="services__info">
согласен, перестарался

2021-09-26 16:46 UTC, BesedinEgor commented on index.html
> +          </ul>
слайды реализую через список, а список ссылок(кнопок) придется тогда выносить из списка слайдов, если мы его не дублируем, я правильно все понял ? иначе я тогда не могу представить, как потом реализовать это через стили

2021-09-26 16:48 UTC, BesedinEgor commented on index.html
> +      <div class="about-us">
окей)

2021-09-26 16:58 UTC, avylando commented on catalog.html
> +                                <span class="control-mark"></span>
Сделать можно по-разному, но лучше через псевдо
+ это будет соответствовать критерию https://up.htmlacademy.ru/htmlcss/32/criteries#HTML-06

2021-09-26 16:59 UTC, avylando commented on index.html
> +        <span class="slider__number"></span>
Да, ты все правильно думал) Решение через псевдо самое универсальное

2021-09-26 17:01 UTC, avylando commented on index.html
> +          </ul>
Список ссылок должен быть отдельно от списка слайдов, так как слайды показываются и скрываются, а ссылки должны оставаться видимыми всегда и играть роль элементов управления

2021-09-26 19:05 UTC, avylando approved these changes
Задание принял, поправь пожалуйста в следующем реквесте верстку слайдов и кнопок в соответствии с комментом

2021-09-26 19:05 UTC, avylando commented on index.html
> +      <div class="about-container">
Честно говоря, название понятнее не стало) секцию можно назвать типа company-info, а этот блок уже about-us
Но смотри сам

2021-09-26 19:06 UTC, merged